spring:
  application:
    name: Auth-Service
  datasource:
    url: jdbc:postgresql://dpg-d35vr2qli9vc738ptucg-a.frankfurt-postgres.render.com/employees_db_54tp
    username: bvm
    password: gk7I712z3feW7jEUxghf4UQM4Z6otDID
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8081


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true