spring:
  application:
    name: Auth-Service
  datasource:
    url: ${DB_URL:jdbc:postgresql://dpg-d35vr2qli9vc738ptucg-a.frankfurt-postgres.render.com/employees_db_54tp}
    username: ${DB_USERNAME:bvm}
    password: ${DB_PASSWORD:gk7I712z3feW7jEUxghf4UQM4Z6otDID}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: ${PORT:8081}


eureka:
  client:
    service-url:
      defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true