spring:
  application:
    name: API-Gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


server:
  port: ${PORT:8080}


services:
  auth:
    name: AUTH-SERVICE
    url: ${SERVICES_AUTH_URL:http://AUTH-SERVICE}
  finance:
    name: FINANCE-SERVICE
    url: ${SERVICES_FINANCE_URL:http://FINANCE-SERVICE}
  report:
    name: REPORTING-SERVICE
    url: ${SERVICES_REPORT_URL:http://REPORTING-SERVICE}


eureka:
  client:
    service-url:
    defaultZone: ${DEFAULT_ZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    instance-id: ${spring.application.name}:${server.port}

# Logging for debugging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: DEBUG
    com.budget.b.lite: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG