spring:
  application:
    name: API-Gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8080

# Fixed service URLs (removed trailing slashes and fixed spacing)
services:
  auth:
    name: AUTH-SERVICE
    url: http://AUTH-SERVICE  # For direct URL fallback
  account:
    name: AUTH-SERVICE  # Both auth and account are on AUTH-SERVICE
    url: http://AUTH-SERVICE

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Logging for debugging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.netflix.discovery: DEBUG
    com.budget.b.lite: DEBUG